# Perfil de desarrollo — configuración permisiva para facilitar el trabajo local
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/postgresql
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
