# Conexión a la DB
spring.datasource.url=jdbc:postgresql://localhost:5432/futbol_db
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Credenciales desde variables de entorno (con fallback para dev local)
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
